_wandb:
    value:
        cli_version: 0.23.1
        code_path: source-book-rating-prediction-main.py
        e:
            hkjvr87ao5yeoknc0bndmec5nqwbx4e9:
                args:
                    - -c
                    - config/config_baseline.yaml
                    - -m
                    - CatBoost
                    - -w
                    - "True"
                    - -r
                    - CatBoost_basic2
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 8
                cpu_count_logical: 8
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "52573995008"
                        used: "37651480576"
                email: qweiop1846@gmail.com
                executable: /data/ephemeral/home/cyj/bin/python
                gpu: Tesla V100-SXM2-32GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "34359738368"
                      name: Tesla V100-SXM2-32GB
                      uuid: GPU-6afcb105-279b-8873-005d-456a77ccec43
                host: instance-17381
                memory:
                    total: "94903173120"
                os: Linux-5.4.0-99-generic-x86_64-with-glibc2.31
                program: /data/ephemeral/home/cyj/code/main.py
                python: CPython 3.10.13
                root: /data/ephemeral/home/cyj/code
                startedAt: "2025-12-06T07:07:11.033508Z"
                writerId: hkjvr87ao5yeoknc0bndmec5nqwbx4e9
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 5
                - 7
                - 8
                - 11
                - 41
                - 49
                - 53
            "2":
                - 1
                - 5
                - 7
                - 8
                - 11
                - 41
                - 49
                - 53
            "3":
                - 2
                - 13
                - 15
                - 16
            "4": 3.10.13
            "5": 0.23.1
            "6": 4.57.3
            "10":
                - 21
            "12": 0.23.1
            "13": linux-x86_64
        visualize:
            feature_importance:
                panel_config:
                    fieldSettings:
                        label: feature
                        value: importance
                    panelDefId: wandb/bar/v0
                    stringSettings:
                        title: Feature Importance
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: feature_importance_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
config:
    value: config/config_baseline.yaml
dataloader:
    value:
        batch_size: 1024
        num_workers: 0
        shuffle: true
dataset:
    value:
        data_path: data/
        valid_ratio: 0.2
device:
    value: cuda
loss:
    value: RMSELoss
lr_scheduler:
    value:
        use: false
memo:
    value: |-
        남겨둘 메모가 있다면 여기에.
        여러 줄로도 작성 가능
        wandb 사용 시 wandb의 description으로 사용됩니다.
metrics:
    value:
        - MSELoss
        - MAELoss
        - RMSELoss
model:
    value: CatBoost
model_args:
    value:
        CatBoost:
            datatype: catboost
            depth: 6
            early_stopping_rounds: 50
            eval_metric: RMSE
            iterations: 1000
            learning_rate: 0.05
            loss_function: RMSE
            use_best_model: true
            verbose: 100
optimizer:
    value:
        args:
            amsgrad: false
            lr: 0.005
            weight_decay: 0.0001
        type: Adam
predict:
    value: false
run_name:
    value: CatBoost_basic2
seed:
    value: 0
train:
    value:
        ckpt_dir: saved/checkpoint
        epochs: 20
        log_dir: saved/log
        resume: false
        save_best_model: true
        submit_dir: saved/submit
wandb:
    value: true
wandb_project:
    value: book-rating-prediction
